Fix python2 'bytes' filehandles for configparser
In python2 they needed opening as wb for unicode. Python3 doesn't need
this.

Fixes:
File "/usr/lib64/python3.6/configparser.py", line 923, in _write_section
  fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'

https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in

Signed-off-by: David Greaves <david.greaves@jolla.com>